substitutions:
  _TAG: 'latest'

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fmw-insurance-portal:${_TAG}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fmw-insurance-portal:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/fmw-insurance-portal:${_TAG}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/fmw-insurance-portal:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fmw-insurance-portal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fmw-insurance-portal:${_TAG}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_API_URL=https://api.bodyf1rst.net/api'

images:
  - 'gcr.io/$PROJECT_ID/fmw-insurance-portal:${_TAG}'
  - 'gcr.io/$PROJECT_ID/fmw-insurance-portal:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
